language: java
sudo: false

jdk:
  - openjdk7

before_install:
  - export MAVEN_OPTS="-Xms128M -Xmx512M"
  - cd parent-pom
  - mvn -Dassembly.skipAssembly -Djarsigner.skip=true clean install
  - cd ..
  - mvn process-resources

before_script:
  - echo $HOME
  - echo $MAVEN_OPTS

script: 
  - mvn clean install -Djarsigner.skip=true -Dmaven.javadoc.skip=true -B -V

install: true

