language: java
sudo: false
jdk:
  - openjdk7
before_install:
  - cd parent-pom
  - mvn -Dassembly.skipAssembly -Djarsigner.skip=true clean install
  - cd ..
  - mvn process-resources
script: mvn -Dassembly.skipAssembly -Djarsigner.skip=true test -B

